@base_url = http://localhost:5001


### show all student
GET {{base_url}}/api/student

### add new student
POST {{base_url}}/api/student
Content-Type: application/json


{
    "name": "jaya",
    "email": "jayasssw@gmail.com"
}

### update student by id
PUT {{base_url}}/api/student/1
Content-Type: application/json

{
    "name": "jayak",
    "email": "jayasss@gmail.com"
}

### delete student by id
DELETE {{base_url}}/api/student/1